name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # Iniciar o servidor diretamente com Node.js (sem Nodemon)
    - name: Start server without nodemon
      run: node src/app.js &

    # Esperar o servidor iniciar
    - name: Wait for server with timeout (60 seconds)
      run: npx wait-on http://localhost:5000 --timeout=60000

    # Executar os testes Cypress
    - name: Run Cypress tests
      run: npx cypress run
